In [9]:
from sklearn.datasets import make_classification
import torch as tp 

In [10]:
print(tp.__version__)

2.9.1+cpu


In [11]:
X,y=make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)


## Making a tensor

In [12]:
X=tp.tensor(X,dtype=tp.float64)
y=tp.tensor(y,dtype=tp.float64)

In [13]:
from torch.utils.data import Dataset,DataLoader


In [14]:
class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels

    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index],self.labels[index]
        

In [15]:
dataset=CustomDataset(X,y)

In [16]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)
for batch_features,batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("-"*50)

tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]], dtype=torch.float64)
tensor([1., 0.], dtype=torch.float64)
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]], dtype=torch.float64)
tensor([1., 0.], dtype=torch.float64)
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [-0.7206, -0.9606]], dtype=torch.float64)
tensor([1., 0.], dtype=torch.float64)
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [ 1.7774,  1.5116]], dtype=torch.float64)
tensor([0., 1.], dtype=torch.float64)
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]], dtype=torch.float64)
tensor([0., 1.], dtype=torch.float64)
--------------------------------------------------
