In [3]:
import torch as tp
import pandas as pd 
from sklearn.preprocessing import StandardScaler
from torch.utils.data import Dataset,DataLoader
from sklearn.model_selection import train_test_split as tts 


In [4]:
data=pd.read_csv('Syntheticdata.csv')
X=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [5]:
X_np=X.to_numpy()
y_np=y.to_numpy()

In [6]:
X_tensor=tp.tensor(X_np,dtype=tp.float64)
y_tensor=tp.tensor(y_np,dtype=tp.float64)

In [7]:
class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels

    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index],self.labels[index]
        

In [9]:
dataset=CustomDataset(X_tensor,y_tensor)
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)
for batch_features,batch_label in dataloader:
    print(batch_features)
    print(batch_label)
    print('-'*50)

tensor([[-0.2346, -2.3053, -0.4225],
        [ 2.1905,  1.7442,  1.1241]], dtype=torch.float64)
tensor([0., 1.], dtype=torch.float64)
--------------------------------------------------
tensor([[ 0.1746, -1.4525,  0.2540],
        [ 1.8862, -0.5516,  1.7058]], dtype=torch.float64)
tensor([1., 1.], dtype=torch.float64)
--------------------------------------------------
tensor([[-0.1924, -0.4627, -2.4459],
        [-1.4635,  0.1497, -1.3996]], dtype=torch.float64)
tensor([0., 0.], dtype=torch.float64)
--------------------------------------------------
tensor([[-1.4154, -1.8819, -0.3315],
        [ 0.2576, -0.5479,  1.7281]], dtype=torch.float64)
tensor([0., 1.], dtype=torch.float64)
--------------------------------------------------
tensor([[ 0.0051, -0.4598, -2.0992],
        [ 0.0686, -0.5047,  0.7861]], dtype=torch.float64)
tensor([0., 1.], dtype=torch.float64)
--------------------------------------------------
tensor([[-0.4206, -1.4870, -1.2665],
        [-0.3921, -1.1489, -1.0023]], 